name: kalpana
channels: 
  - javascript
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.9
  - torchvision=0.8
  - pytorch>=1.7.0
  - numpy>=1.16.6
  - future>=0.17.1
  - sphinx
  - numpy
  - pandas>=1.0.0
  - scikit-learn
  - scipy
  - spacy
  - nltk
  - matplotlib